version: '3.4'

services:
  apiabsensimobile:
    image: api-absensi-mobile
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    environment:
      - NODE_ENV=production
      - MONGODB_URI=$MONGODB_URI
      - API_KEY=$API_KEY
      - SECRET=$SECRET
      - API_BASE_URl=$API_BASE_URl
    ports:
      - '8082:8082'
