name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    # - uses: actions/checkout@v2
    #   with:
    #     path: "api-absensi-mobile"

    # - name: Repository checkout
    #     uses: actions/checkout@v2
    - name: Connects to VPS via SSH
      uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            echo ---Building and starting up docker---