name: Deploy

on: 
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: Connects to VPS via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        script: | 
        echo ---Building and starting up docker---
        cd ~/absensi_mobile/api-absensi-mobile
        git pull origin master
        git status
        docker-compose up -d
        echo ---Containers up---