name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: Connects to VPS via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        script: ls -al